# Generated by Django 5.0.3 on 2024-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
