# Generated by Django 5.0.3 on 2024-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shortnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit_channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='author_image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
