# Generated by Django 5.0.3 on 2024-06-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reddit_channel_alter_shortnews_author_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnews',
            name='author_pic',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
