# Generated by Django 5.0.3 on 2024-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_shortnews_author_pic_alter_shortnews_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnews',
            name='image_height',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortnews',
            name='image_width',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
