# Generated by Django 5.0.3 on 2024-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_shortnews_image_height_shortnews_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnews',
            name='video',
            field=models.TextField(null=True),
        ),
    ]
