# Generated by Django 5.0.3 on 2024-07-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_shortnews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnews',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
