# Generated by Django 5.0.3 on 2024-07-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_shortnews_likes_shorts_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortnews',
            old_name='author_image_url',
            new_name='reddit_url',
        ),
    ]
